### ISSUE TITLE
Warning after upgrading to Ruby version 2.7.2

### ISSUE THREAD

**Issue by fydelio** [mdp/rotp#106]
After upgrading to Ruby version 2.7.2 I get the following notice when running `rails test`

> /Users/fydelio/.rvm/gems/ruby-2.7.2/gems/rotp-2.1.2/lib/rotp/totp.rb:56: warning: URI.escape is obsolete

<img width="1553" alt="Bildschirmfoto 2020-12-15 um 14 11 07" src="https://user-images.githubusercontent.com/26507829/102219607-fbea5680-3edf-11eb-983a-0606eaa7f61e.png">

**Comment by dentarg** [comment]
You are using a very old version of rotp, please upgrade: https://github.com/mdp/rotp/blob/62874be71d74380d252c73409dd81da08b021497/CHANGELOG.md#401

**Comment by fydelio** [comment]
I noticed, that the [devise-two-factor gem](https://github.com/tinfoil/devise-two-factor) is depending on a very old version of this gem.
