### ISSUE TITLE
Undefined method verify_with_drift

### ISSUE THREAD

**Issue by omarluq** [mdp/rotp#112]
Working on upgrading devise-two-factor from 3.x to 4.x and a part of that was upgrading the OTP gym to 6.0, however now I'm getting the error mentioned in the title 

```
undefined method 'verify_with_drift' for u003cROTP::TOTP
```
from looking at the code base it seems that the method was removed but the CHANGELOG doesn't mention anything on deprecating the method or replacing it. 
I also cant seem to find any other issues related to this. Any help would be appreciate

**Comment by mdp** [comment]
Sorry, this was a mistake in the v4.0 CHANGELOG documentation. verify_with_drift was merged into just 'verify' now with the optional param 'drift_ahead' and 'drift_behind'.

I've updated the CHANGELOG.

For your use case, `verify_with_drift(otp, drift)` should just become `verify(otp, drift_behind: drift)`

**Comment by omarluq** [comment]
Thanks for clarifying 🙌🏻
