### ISSUE TITLE
rotp and mathn

### ISSUE THREAD

**Issue by askprod** [mdp/rotp#123]
Hi,

We are using this gem with Ruby version 2.5.9, but we have the gem `mathn` manually installed (which was included by default until ruby 2.5) 
We've had trouble debugging but we notice that with the `mathn` gem, dividing numbers gives you fractions instead of integers, therefore [in this part on the code of rotp](https://github.com/mdp/rotp/blob/2be11551ac4982670d526ceef4a5db985d0f626a/lib/rotp/totp.rb#L78), we had to monkey patch `timeint(time) / interval` and use `(timeint(time) / interval).to_i` (which is the same result) to make it work, as later on it was trying to compare fractions with byte strings which caused some issues.

Would it be something you would like to include in the original code to avoid problems with older versions of ruby ?

Thank you !

**Comment by mdp** [comment]
I think in this case it's probably best to keep monkey patching ROTP for this use case. Mathn was deprecated ~9 years ago in Ruby 2.2.0, so it seems like it's probably not an issue for most users today. There's actually a few places where we do math operations with the assumption that it will be an integer, so it would actually require a few more code changes to cover all the areas where mathn changes the default behavior of Ruby.
