### ISSUE TITLE
Expired code if internal was set more than 1 minute

### ISSUE THREAD

**Issue by cthungIT** [mdp/rotp#125]
When set interval is 300

test_time = 'Wed, 12 Apr 2023 11:49:59 +08 +08:00'.to_datetime
otp = ROTP::TOTP.new(token, issuer: 'test', interval: 300)
code = otp.at(test_time)

now = 'Wed, 12 Apr 2023 11:50:01 +08 +08:00'.to_datetime
otp.verify(code, at: now) => nil

above code is only valid in 11:45:00-> 11:49:59

**Comment by mdp** [comment]
Yeah, an interval doesn't mean it's valid for any 300 seconds, but it's valid for an interval of 300 seconds. So for example Unix time 0 to 299, and then it's invalid again at 300.

So if you pick a random time, you don't actually know where it falls in the interval until you do the conversion to unix time and 'round' it down to the nearest 300 second interval.

You can see this in the totp.rb code - https://github.com/mdp/rotp/blob/main/lib/rotp/totp.rb#L77

Using your example above

```
irb(main):041:0> Time.parse("Wed, 12 Apr 2023 11:49:59 +08 +08:00").to_i / 300
=> 5604237
irb(main):042:0> Time.parse("Wed, 12 Apr 2023 11:50:00 +08 +08:00").to_i / 300
=> 5604238
```

11:49:59 is just on the edge of a new 300 second interval. But the code at 11:50:00 will work until 11:54:59 as expected.

```
irb(main):044:0> Time.parse("Wed, 12 Apr 2023 11:54:49 +08 +08:00").to_i / 300
=> 5604238
irb(main):045:0> Time.parse("Wed, 12 Apr 2023 11:55:00 +08 +08:00").to_i / 300
=> 5604239
```
