### ISSUE TITLE
Interval doesn't work as expected

### ISSUE THREAD

**Issue by fltiago** [mdp/rotp#28]
Hello, I'm trying to set an interval of 30 days, but when I check if that key is still valid on that interval I'm getting false as return.

Example:
```ruby
THIRTY_DAYS_IN_SECONDS = 2592000
start_date = Time.now
rotp = ROTP::HOTP.new("test", interval: THIRTY_DAYS_IN_SECONDS, digits: 8)
key = rotp.at(start_date)
sleep(5)
rotp2 = ROTP::TOTP.new("test", interval: THIRTY_DAYS_IN_SECONDS, digits: 8)
rotp.verify(key)
=> true
rotp2.verify(key)
=> true
rotp2.verify(key, start_date)
=> true
rotp2.verify(key, start_date + 2591000.seconds)
=> false
rotp2.verify(key, start_date + 2101000.seconds)
=> true
rotp2.verify(key, 26.days.from_now)
 => false 
rotp2.verify(key, 25.days.from_now)
 => true 
```

My guess is that the problem is with [`timecode`](https://github.com/mdp/rotp/blob/master/lib/rotp/totp.rb#L62-L64) because it's a integer division and some time is lost.

What you think? Am I doing something wrong?

**Comment by mdp** [comment]
The above comment is correct. An example for 30 second intervals:

Lets say it's 4:40:35pm, the time used for the token would be 4:40:30

If it was currenly 4:40:45, and you added 20 seconds, it would be 4:41:05 and the token would be 4:41:00
