### ISSUE TITLE
Issuer causes invalid barcode

### ISSUE THREAD

**Issue by OBCENEIKON** [mdp/rotp#42]
When adding an issuer, the barcode generated is invalid according to Google Authenticator. 

I've tried it with just the issuer parameter.
```
base32secret = ROTP::Base32.random_base32
totp = ROTP::TOTP.new(base32secret, issuer: 'Example Issuer')
qrcode = totp.provisioning_uri('user@example.com')
```
![img_0601](https://cloud.githubusercontent.com/assets/164630/7848543/5a5abaae-0492-11e5-9dfc-dd0ef4d0f802.PNG)

I've tried it with a issuer label prefix and a issuer parameter, per [Google](https://github.com/google/google-authenticator/wiki/Key-Uri-Format#label).
```
base32secret = ROTP::Base32.random_base32
totp = ROTP::TOTP.new(base32secret, issuer: 'Example Issuer)
qrcode = totp.provisioning_uri('Example Issuer:user@example.com')
```
![img_0602](https://cloud.githubusercontent.com/assets/164630/7848548/63dd9880-0492-11e5-8ce9-85a3feac97cc.PNG)

**Comment by mdp** [comment]
Which OTP program on iOS are you using? I'm assuming this is a param encoding issue, but I'd like to replicate it on my device first to test it out.

Thanks,
Mark

**Comment by mdp** [comment]
Deleted last comment, sorry, just saw that you mentioned it was Google Authenticator.

Let me keep looking into this.

**Comment by mdp** [comment]
I can't seem to replicate this under Google Authenticator on iOS or Android. Can you post the provisioning uri you're getting back at the last step?

I'm running the following:

```
base32secret = ROTP::Base32.random_base32
=> "ltk6coo7weu6rfhz"
totp = ROTP::TOTP.new(base32secret, issuer: 'Example Issuer')
=> #<ROTP::TOTP:0x007fc03c0494e0 @interval=30, @issuer="Example Issuer", @digits=6, @digest="sha1", @secret="ltk6coo7weu6rfhz">
qrcode = totp.provisioning_uri('user@example.com')
=> "otpauth://totp/user@example.com?issuer=Example+Issuer&secret=ltk6coo7weu6rfhz"
```
Then turning this into a qrcode I have the following:

![QRCode](http://chart.apis.google.com/chart?cht=qr&chs=300x300&chl=otpauth%3A//totp/user%40example.com%3Fissuer%3DExample%2BIssuer%26secret%3Dltk6coo7weu6rfhz&chld=H|0)

If you scan the above, are you getting back the same error? What service are you using to generate the QRCode?

Thanks,
Mark

**Comment by mdp** [comment]
Closing for now. Reopen if needed.
