### ISSUE TITLE
Is it possible to only have one valid OTP at a given time?

### ISSUE THREAD

**Issue by monfresh** [mdp/rotp#46]
Hi. I'd like to implement something like what PayPal does, but I haven't been able to figure out if it's possible with rotp.

When you request an initial OTP from PayPal to be sent to your mobile phone, you receive the code and a message that it will expire in 5 minutes. If you then request a new OTP, the old one immediately becomes invalid, but the new one remains valid for 5 minutes.

How can this be achieved with rotp?

Thanks!

**Comment by mdp** [comment]
So I'd probably just do this manually without involving ROTP. ROTP (The HOTP/TOTP spec) is based on the idea of the end user and the server sharing a secret. This allows the end user to generate a code on their device (ex Google Authenticator) and you don't need to send it to them. This works great for many cases, but it doesn't allow you to easily create a new code on the fly, instead you have to just wait until the next code is generated(30s-60s). The best example of this is Google 2FA with the Google Authenticator app.

To replicate the Paypal 2FA experience, I'd just store a server side generated code and expiration on the user and send it to their phone (SMS or some other push). If they request a new token, just regenerate a new code and overwrite the old one. As for generating the code, just use a cryptographically secure random number generator (SecureRandom) to create the 6-8 digit code.

The benefits of the ROTP(TOTP) is that you don't have to send codes to the end user (no SMS cost). The downside is that the end user has to install an app and set it up properly.

Hope that helps. Feel free to reopen if you have any other questions.

**Comment by monfresh** [comment]
Thanks! That was very clear and helpful.
