### ISSUE TITLE
ROTP Giving wrong code

### ISSUE THREAD

**Issue by amitiitm** [mdp/rotp#55]
I have implemented Google authenticator by ROTP 2 Years back and it stopped working few months back. Code generated by Google and by ROTP on my server are different. I have checked the server timings, my mobile timings and also updated the Gem with latest version, even then its not working. I have also tried this sample snippet of code
```
require 'rubygems'
require 'rotp'
totp = ROTP::TOTP.new("JBSWY3DPEHPK3PXP")
p "Current OTP: #{totp.now}"
```

But it is giving different codes all the time, Please suggest ????

**Comment by sahilchopra** [comment]
+1

**Comment by mdp** [comment]
So testing this with the latest gem and the latest Google Authenticator on iOS, I'm seeing the same codes.

Here's the provisioning barcode for the sample code you gave
![qrcode](http://chart.apis.google.com/chart?cht=qr&chs=300x300&chl=otpauth%3A//totp/test%3Fsecret%3DJBSWY3DPEHPK3PXP&chld=H|0)

I scanned it with my phone and verified that it matched the output from
`p "Current OTP: #{totp.now}"`

Can you scan the above QR provisioning code and verify? Thanks

**Comment by mdp** [comment]
Closing this for now. Please re-open if it's not resolved.

**Comment by amit1937** [comment]
Yeah we have found the solution for the same, we need to make the local system time settings to manual and then map our mobile time. When both the time are same then it is generating same code.
