### ISSUE TITLE
Missing ":" in Label in Provisioning URI

### ISSUE THREAD

**Issue by caryfitzhugh** [mdp/rotp#56]
I'm looking at the examples here: https://daplie.github.io/browser-authenticator/
In concert with this spec from google: https://github.com/google/google-authenticator/wiki/Key-Uri-Format

Here is their example:
```
otpauth://totp/ACME%20Co:john.doe@email.com?secret=HXDMVJECJJWSRB3HWIZR4IFUGFTMXBOZ&issuer=ACME%20Co&algorithm=SHA1&digits=6&period=30
```
It appears that their label is 
```
ACME%20Co:john.doe@email.com
```

The spec says that the label should be composed of
```
  issuer ":" name
```

The rotp implementation seems to omit the ":" in between the two values.
https://github.com/mdp/rotp/blob/master/lib/rotp/totp.rb#L67
```
    encode_params("otpauth://totp/#{issuer_string}#{URI.encode(name)}", params)
```

I'm more than happy to put in a PR to fix this, but wondering if others have seen this / decided not to fix it, etc.  Is the correct approach to just put the ":" on the front of the name as you pass it into the provisioning_uri method?

**Comment by mdp** [comment]
Hey,

Yeah, so this should be the way it happens now. @sbc100 implemented this pretty recently.

In line 60 the ':' is appended to the issuer - https://github.com/mdp/rotp/blob/master/lib/rotp/totp.rb#L60

This is what I have now:

```
totp = ROTP::TOTP.new("JBSWY3DPEHPK3PXP", :issuer => 'MyService')
totp.provisioning_uri('m@mdp.im')
=> "otpauth://totp/MyService:m@mdp.im?secret=JBSWY3DPEHPK3PXP&issuer=MyService"
```

Are you on the latest version?

Thanks

**Comment by caryfitzhugh** [comment]
I'm all set now. thanks!
