### ISSUE TITLE
ROTP::Base32.random_base32 OTP don't match with Google Authenticator OTP On Amazone

### ISSUE THREAD

**Issue by sahilchopra** [mdp/rotp#57]

**Comment by mdp** [comment]
Hey, sorry, not sure I totally understand what's happening here. Can you give me more details about the issue.

Thanks

**Comment by sahilchopra** [comment]
It was issue on Amazon server. UTC time was 6 mins ahead. I need to install ntp. 

Plz close this issue

**Comment by mdp** [comment]
No problem, thanks
