### ISSUE TITLE
How to generate manual key for Google Authenticator?

### ISSUE THREAD

**Issue by generationloss** [mdp/rotp#72]
Google Authenticator provides the option to manually enter a 16-digit key as opposed to scanning the QR code.  The "secret" field in the provisioning uri is much longer than 16 digits, so that's not it...I've spent hours Googling and pawing through source code and can't find an answer to this seemingly straightforward question - hoping you can be of help.

**Comment by Nitrino** [comment]
`ROTP::Base32.random_base32` returns a 16-digit secret code.
You can just use it for Google Authenticator.

**Comment by mdp** [comment]
The later versions of rotp increased the secret length (32 now), but you can just use a 16 digit secret and get the same result as Google uses. Just shorten the random secret code to 16 digits.
