### ISSUE TITLE
Can't find "verify_with_drift_and_prior" in the codebase

### ISSUE THREAD

**Issue by danlaffan** [mdp/rotp#74]
I am trying to follow the installation instructions on verifying OTP tokens that have not been used already, using the suggested method `totp.verify_with_drift_and_prior` (as described in the README) but it doesn't work and I can't find the method in the gem's codebase.  

Is this method in some new branch?  I'm using v3.1.0 of the gem.

Cheers, Dan

**Comment by mdp** [comment]
Hey Dan,

This should be in version 3.2 and greater, unfortunately. The latest version of this gem is 3.3.1

The code can be found here:
https://github.com/mdp/rotp/blob/master/lib/rotp/totp.rb#L59

**Comment by danlaffan** [comment]
@mdp - thank you, that worked for me.
