### ISSUE TITLE
How to regenerate token if verify_with_drift_and_prior was verified?

### ISSUE THREAD

**Issue by kesha-antonov** [mdp/rotp#76]
Hello!

```
otp = ROTP::TOTP.new(secret).now
...
rotp = ROTP::TOTP.new(secret)
rotp.verify_with_drift_and_prior(otp, 30, last_verify_at) => true
```
When I logout and try to login within 30 seconds I get error because otp was verified already. And I have to wait 0-30 seconds to try with new otp.

Is it possible to do ```ROTP::TOTP.new(secret).now``` to generate new value that would be valid with ```rotp.verify_with_drift_and_prior(otp, 30, last_verify_at)```?

**Comment by mdp** [comment]
The OTP is basically `hmac(current time period, secret)`, so it's always going to be the same for the current time. I'm not sure of any other way to generate a new value for the same time period.

I think yout options are:
1. Wait the 30 seconds for a new code
2. Chose to allow the same code to be used more than once (obviously less secure).

Unforntunately, OTP is not very user friendly. If you're implementing it today, I'd look at supporting U2F as an additional second factor.

**Comment by kesha-antonov** [comment]
Ok! Thanks @mdp  !
