### ISSUE TITLE
README.md is inaccurate for `totp.verify_with_drift_and_prior`

### ISSUE THREAD

**Issue by samueltangz** [mdp/rotp#77]
`verify_with_drift_and_prior` returns `nil` (not `false`) when OTP is invalid.

**Comment by luongvo209** [comment]
Could you elaborate more on your case @samueltangz ? 
I did a quick check of the source code. And the result should come from 
https://github.com/mdp/rotp/blob/c82113eee6c9e7d0a03df8cf65ea50a2653c3916/lib/rotp/otp.rb#L86 
which, as you can see, always return a boolean result of a comparison with 0

**Comment by samueltangz** [comment]
Sorry for being unclear...  when using `totp.verify_with_drify_and_prior`, the doc said that it would return the timestamp when the token is valid, and `false` otherwise:
https://github.com/mdp/rotp#preventing-reuse-of-time-based-otps

However, from the line of code below, it returns `nil` instead of `false`.
https://github.com/mdp/rotp/blob/master/lib/rotp/totp.rb#L72

**Comment by luongvo209** [comment]
@samueltangz I think I know what you mean now. Just submitted a PR for that ^

**Comment by samueltangz** [comment]
seems legit. many thanks!

**Comment by mdp** [comment]
Updated the v3.x docs to reflect this error. It's been out in the wild for a while now and rather than fix it in v3.x, I'm going to let it stand in an abundance of caution to not break anyone implementation, as the latest version (4.x) doesn't have this issue.
