### ISSUE TITLE
Feature Request SHA256 based TOTP

### ISSUE THREAD

**Issue by tristanmorgan** [mdp/rotp#83]
I was wondering if you'd consider supporting SHA256 based TOTP's? I'm using some services that are appending a "algorithm=SHA256" parameter to their otpauth URL's
(see https://github.com/google/google-authenticator/wiki/Key-Uri-Format)

if I have time I may follow up with a PR.

**Comment by mdp** [comment]
I'm happy to merge in a PR that enables it. Likewise, if I have time, I'll add it myself.

**Comment by mdp** [comment]
Sorry, but looking at it now, I think this is already in there... just not very well documented (something I should fix).

https://github.com/mdp/rotp/blob/master/lib/rotp/otp.rb#L16

**Comment by tristanmorgan** [comment]
Sorry, it was even in the change log but I missed it.

> 3.3.0
> Add digest algorithm parameter for non SHA1 digests - #62 from @btalbot

**Comment by tristanmorgan** [comment]
But on the cli...
