### ISSUE TITLE
wrong code - oauthtool vs mdp/rotp 

### ISSUE THREAD

**Issue by clarkewd** [mdp/rotp#86]
I recently had to add a new code. This one was much longer than the others. I found that mdp/rotp was giving a different code than Google Authenticator. I tested with the CLI and found that it was being handled correctly via oathtool but not via rotp:

This is correct:

	oathtool --totp -v -b IFADSABWAA2AAMAAHFAFCABRAAWQAQIAIFADOABXAAWQANAAG4ADOACDAAWQAQQAIYAFIACFAAWQARIAGQAFFABVAA3AANIAHAAFIABYAAYAAQYAIMAA

	Hex secret: 414039003600340030003940510031002d0041004140370037002d0034003700370043002d0042004600540045002d00450034005280350036003500380054003800300043004300
	Base32 secret: IFADSABWAA2AAMAAHFAFCABRAAWQAQIAIFADOABXAAWQANAAG4ADOACDAAWQAQQAIYAFIACFAAWQARIAGQAFFABVAA3AANIAHAAFIABYAAYAAQYAIMAA====
	Digits: 6
	Window size: 0
	Step size (seconds): 30
	Start time: 1970-01-01 00:00:00 UTC (0)
	Current time: 2019-05-09 15:47:06 UTC (1557416826)
	Counter: 0x31824A6 (51913894)

	861917

Run at the same time, this produces a different code:

	puts ROTP::TOTP.new('IFADSABWAA2AAMAAHFAFCABRAAWQAQIAIFADOABXAAWQANAAG4ADOACDAAWQAQQAIYAFIACFAAWQARIAGQAFFABVAA3AANIAHAAFIABYAAYAAQYAIMAA').now
	# 413689

I'm using the latest version of `mdp/rotp` and `ruby 2.4.1`. What am I doing wrong?

**Comment by mdp** [comment]
Yes, this is a bug in how ROTP decodes Base32's with secrets that are not multiples of 8 (in this case 116 characters, or 580 bits, or 72.5 bytes long). I've been meaning to clean up the way ROTP handles Base32 decoding so I'll have something up tonight as a fix. 

Thanks for finding and reporting this.

**Comment by mdp** [comment]
Sorry for the delay on this, work stuff came up. I fixed this and put it into v5.0.0

**Comment by clarkewd** [comment]
working perfectly - thank you!
