### ISSUE TITLE
Wrong number of arguments error

### ISSUE THREAD

**Issue by prvinuch** [mdp/rotp#87]
Hi Team,
we are facing issue while trying to call otp_code method.

$gem_library_root/vendor/bundle/ruby/2.3.0/gems/rotp-4.1.0/lib/rotp/totp.rb:17
$gem_library_root/vendor/bundle/ruby/2.3.0/gems/active_model_otp-1.2.0/lib/active_model/one_time_password.rb:77

as far as I dig into, I found this.
the issue is in arguments, it seems the latest rotp gem have updated below method to accept only 1 argument insted of 2 as compared to older version (3.3.1)
 as per rotp-4.1.0 
![otp_code_rotp_gem_screenshot](https://user-images.githubusercontent.com/6958051/58451710-33dd4d80-8132-11e9-97b4-b119e4393d30.png)
`

       def at(time)
          generate_otp(timecode(time))
        end

` 
	
 as per rotp-3.3.1
     `

      def at(time, padding=true)
          unless time.class == Time
               time = Time.at(time.to_i)
          end	  
          generate_otp(timecode(time), padding)
     end
`

since the optional parameter has been removed, the active_model_otp-1.20 gem is giving error at line number 77

![otp_code_error_screenshot](https://user-images.githubusercontent.com/6958051/58451711-3475e400-8132-11e9-9948-7e85bf795cd6.png)

I can make changes in the gem but not sure what else will break, active-model gem was last updated in 2015, and rotp updated few months back.
please suggest suitable method, if I revert back to previous gem version of rotp then what else would break.

kinldy help.

**Comment by mdp** [comment]
Hi there,

It looks like ActiveModel OTP will need to be updated to either lock in the version at '~> 3.3', or it will need to be updated to use the latest API. The best option is probably the latter. Either way, you'll need to either for the code or submit a pull request to the ActiveModelOTP team.

Hope that helps
