### ISSUE TITLE
Missing tag for rotp v5.0.0

### ISSUE THREAD

**Issue by thomasdziedzic** [mdp/rotp#88]
5.0.0 was released without a corresponding tag in github, could you please add it?
https://rubygems.org/gems/rotp/versions/5.0.0

My guess is that this is the commit that needs to be tagged:
https://github.com/mdp/rotp/commit/c38462855747b62607b8475d9b45c4cfd92ba66b

**Comment by mdp** [comment]
Sorry about that. Updated
