### ISSUE TITLE
Please explain what happened to #random_base32

### ISSUE THREAD

**Issue by jayqui-omada** [mdp/rotp#92]
Hello,

It's helpful to see on your README that "`ROTP::Base32.random_base32` is now `ROTP::Base32.random` and the argument has changed from secret string length to byte length to allow for more precision."

However, it is unlcear what is meant by "has changed from secret string length to byte length". Will you please explain?

Also, it looks like the [rdoc](https://rubydoc.info/github/mdp/rotp/master/ROTP/Base32) for this class is still out of date.

**Comment by mdp** [comment]
Sorry, I apparently missed this issue in my feed. 

I've recreated the Yard docs (for some reason they weren't updating)
https://www.rubydoc.info/github/mdp/rotp/master/ROTP/Base32

You can see that there is still `random_base32` for backwards compatibility, but Base32.random was created to make it easy to understand the entropy of a secret. For example, if you wanted >16 bytes(128bits) of entropy with a Base32 secret, you needed to calculate Math.ceil(bits/5), or in this case a 26 character secret.

With Base32.random, you can just pass in the byte length instead. So `Base32.random(16)` for example. By default it's 20 bytes(160bits).
