### ISSUE TITLE
How to save a secret code to a user

### ISSUE THREAD

**Issue by codeundercoverdev** [mdp/rotp#93]
It doesn't seem it's possible in Rails (using Rails 5) to persist a rotp object between requests? I must be missing something because this seems like the most basic usecase of this library. I want a user to sign up with their phone number and then we generate a pin and send it back to them.

You would think you could do something like this:

```
class User < ApplicationRecord
    before_validation :generate_otp_secret_key, on: :create
    def generate_otp_secret_key
	self.otp_secret_key = ROTP::TOTP.new("base32secret3232", issuer: "Tap")
    end
end
```

But since  `ROTP::TOTP.new` returns its own object type, you can't save it to the database. And since you require the original object to verify the pin with `.verify`, it seems the functionality of generating a pin for a user to verify them is impossible with this library.  Given that this is the purpose of the library, I'M SURE I'M MISSING SOMETHING BASIC.  Is there a method you're supposed to put in the model that's not mentioned in the readme?  Can someone tell me what I'm missing?

The readme gives this example:
```
User.find(someUserID)
totp = ROTP::TOTP.new(user.otp_secret)
```
but they never say where `user` actually comes from.  I tried adding `user = ` to the beginning of the first line but that doesn't seem to work either.

**Comment by mdp** [comment]
The thing you're saving to the User record is the secret. So in your example:
```
class User < ApplicationRecord
    before_validation :generate_otp_secret_key, on: :create
    def generate_otp_secret_key
	self.otp_secret_key = ROTP::Base32.random #Outputs a string
    end
end
```

Then when you can get the TOTP by passing in that random base32 string:

```
totp = ROTP::TOTP.new(user.otp_secret_key)
totp.now # => "492039"
```

Sorry, the pseudo-code in the README isn't complete. To be more clear, it should read `user = User.find(someUserId)`. I'll fix this.

Feel free to re-open if you have other questions.
